"""empty message

Revision ID: 7953966789b7
Revises: f8e7f36be0fa
Create Date: 2024-12-18 16:08:18.350813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7953966789b7'
down_revision = 'f8e7f36be0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
